FROM node:20 as builder

WORKDIR /app
COPY . .
ENV CI=0
RUN npm ci && npm run storybook:build

FROM nginx
COPY --from=builder /app/storybook-static /usr/share/nginx/html
RUN mkdir /etc/nginx/templates
COPY .nginx/storybook.conf.template /etc/nginx/templates/default.conf.template
